### PR TITLE
Reposition and animate background skytrains

### PR DESCRIPTION
**Pull request by acchiang**

### CODE REVIEW

**Comment by tommytwm** [comment]
I think I would prefer if the trains were to either flow in one direction (forwards for canada line, backwards for expo line) and disappear from the page entirely instead of swinging back and forth (just makes sense for a train to do that), and the trains would reappear again after some time. This is just an animation design preference. Other than that, looks good!

**Comment by acchiang** [comment]
@tommytwm that makes sense! so maybe we'll have them move in one direction, fade away (just in case the train is still in view, but it should be out of view by then), and reset to the original position?

**Comment by tommytwm** [comment]
Yeah, that’s kind of what I had in mind (except the fade part)

**Comment by patkarns** [comment]
The train won't line with the track on my screen (15" mac). Probably cause it's a different dimension.

Screen Shot 2020-05-26 at 2 39 27 AM

**Comment by patkarns** [comment]
Also not sure if this is the intended behavior or if my screen is just wider. The train only goes this much left/right: (won't completely disappear off-screen).

Screen Shot 2020-05-26 at 2 41 45 AM
Screen Shot 2020-05-26 at 2 41 35 AM

**Comment by acchiang** [comment]
i've made changes to make sure the trains move in one direction each, disappear off screen, and stay on the tracks :)

**Pull request merged**
